config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :cargoes, :ship_ports, :routes, :ships 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cargoe.rb
class Cargoe < ApplicationRecord
  belongs_to :route
end

app/models/route.rb
class Route < ApplicationRecord
  belongs_to :ship
  belongs_to :from_port, class_name: "ShipPort"
  belongs_to :to_port, class_name: "ShipPort"
end

app/models/ship.rb
class Ship < ApplicationRecord
end

app/models/ship_port.rb
class ShipPort < ApplicationRecord
end

app/models/ships_log.rb
class ShipsLog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cargoes_controller.rb
class CargoesController < ApplicationController
  def index
    if params[:sort] == "від нецінного"
      @cargoes = Cargoe.order(:value).reverse_order
    elsif params[:sort] == "від цінного"
      @cargoes = Cargoe.order(:value)
    elsif params[:sort] == "назва(від а до я)"
      @cargoes = Cargoe.order(:name)
    elsif params[:sort] == "назва(від я до а)"
      @cargoes = Cargoe.order(:name).reverse_order
    elsif params[:sort] == "від легшого"
      @cargoes = Cargoe.order(:mass)
    elsif params[:sort] == "від важчого"
      @cargoes = Cargoe.order(:mass).reverse_order
    elsif params[:search_for] == "назвою"
      @cargoes = Cargoe.where(name: params['search'])
    elsif params[:search_for] == "цінністю"
      @cargoes = Cargoe.where(value: params['search'])
    elsif params[:search_for] == "масою"
      @cargoes = Cargoe.where(mass: params['search'])
    elsif params[:search_for] == "реєстраційним номером"
      @cargoes = Cargoe.where(reg_number: params['search'])
    else
      @cargoes = Cargoe.order(:id)
    end
  end

  def new;  end

  def create
    Cargoe.create!(cargoe_params)
    redirect_to cargoes_path
  end

  def edit
    @cargoe = Cargoe.find(params['id'])
  end

  def update
    cargoe = Cargoe.find(params['id'])
    cargoe.update(cargoe_params)
    redirect_to cargoes_path
  end

  def destroy
    cargoe = Cargoe.find(params['id'])
    cargoe.delete
    redirect_to cargoes_path
  end

  private

  def cargoe_params
    params.require(:cargoe).permit(
      :name, :value, :mass, :reg_number, :route_id
    )
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  def index
    @routes = Route.order(:id)
  end

  def new;  end

  def create
    Route.create!(route_params)
    redirect_to routes_path
  end

  def edit
    @route = Route.find(params['id'])
  end

  def update
    route = Route.find(params['id'])
    route.update(route_params)
    redirect_to routes_path
  end

  def destroy
    route = Route.find(params['id'])
    route.delete
    redirect_to routes_path
  end

  private

  def route_params
    params.require(:route).permit(
      :ship_id, :from_port_id, :to_port_id, :departure_time, :arrival_time
    )
  end
end

app/controllers/ship_ports_controller.rb
class ShipPortsController < ApplicationController
  def index
    @ports = ShipPort.all
    if params['search_name'].present?
      @ports = @ports.where(name: params['search_name'])
    end
    ordering_direction = params[:sort] == "від я до а" ? :desc : :asc
    @ports = @ports.order(name: ordering_direction)
  end

  def new;  end

  def create
    ShipPort.create!(port_params)
    redirect_to ship_ports_path
  end

  def edit
    @port = ShipPort.find(params['id'])
  end

  def update
    port = ShipPort.find(params['id'])
    port.update(name: params['porte']['name'],
                location: params['porte']['location'])
    redirect_to ship_ports_path
  end

  def destroy
    port = ShipPort.find(params['id'])
    port.delete
    redirect_to ship_ports_path
  end

  private

  def port_params
    params.require(:ship_port).permit(:name, :location)
  end
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  def index
    @ships = Ship.all
    if params['search_name'].present?
      @ships = @ships.where(name: params['search_name'])
    end
    ordering_direction = params[:sort] == "від я до а" ? :desc : :asc
    @ships = @ships.order(name: ordering_direction)
  end

  def new;  end

  def create
    Ship.create!(ship_params)
    redirect_to ships_path
  end

  def edit
    @ship = Ship.find(params['id'])
  end

  def update
    ship = Ship.find(params['id'])
    ship.update(ship_params)
    redirect_to ships_path
  end

  def destroy
    ship = Ship.find(params['id'])
    ship.delete
    redirect_to ships_path
  end

  private

  def ship_params
    params.require(:ship).permit(
      :reg_number, :name, :load_capacity
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    ship = Ship.all
    @ships = ship.size
    rout = Route.all
    @routes = rout.size
    cargoe = Cargoe.all
    @cargoes = cargoe.size
    port = ShipPort.all
    @ports = port.size
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cargoes_helper.rb
module CargoesHelper
end

app/helpers/ports_helper.rb
module PortsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cargoes/edit.html.erb
<h3>Змінити вантажу №<%= @cargoe.id %></h3>
<%= form_for @cargoe, method: :patch do |f| %>
  <%= f.label :name, "Назва вантажу" %>
  <div><%= f.text_field :name %></div>
  <%= f.label :value, "Цінність вантажу" %>
  <div><%= f.select :value, ['мінімальна', 'комфорт', 'висока'] %></div>
  <%= f.label :mass, "Маса" %>
  <div><%= f.number_field :mass %></div>
  <%= f.label :reg_number, "Реєстраційний номер" %>
  <div><%= f.number_field :reg_number %></div>
  <%= f.label :reg_number, "Id маршруту" %>
  <div><%= f.select(:route_id, Route.all.collect { |route| [route.id] }) %></div>
  <div><%= f.submit 'Зберегти' %></div>
<% end %>

app/views/cargoes/index.html.erb
<div class="page">
  <main>
    <center><h1>Виведення данних про вантажі</h1></center>
    <table border="1">
      <tr>
       <th>Id</th>
       <th>Назва вантажу</th>
       <th>Цінність</th>
       <th>Маса</th>
       <th>Реєстраційний номер</th>
       <th>Id маршруту</th>
      </tr>
      <% @cargoes.each do |cargoe| %>
      <tr>
        <td><%= cargoe.id %></td><td><%= cargoe.name %></td>
        <td><%= cargoe.value %></td><td><%= cargoe.mass %></td>
        <td><%= cargoe.reg_number %></td><td><%= cargoe.route.id %></td>
        <td><%= link_to 'Редагувати', edit_cargo_path(cargoe) %></td>
        <td><%= link_to 'Видалити', cargo_path(cargoe), method: :delete %></td>
      </tr>
      <% end %>
    </table>
    <h3>Сортування</h3>
    <%= form_with url: cargoes_path, method: :get do |f| %>
      <div><%= f.select :sort, ['назва(від а до я)', 'назва(від я до а)',
                                'від нецінного', 'від цінного',
                                'від легшого', 'від важчого'] %>
      </div>
      <br>
      <%= submit_tag 'Сортувати' %>
    <% end %>
    <h3>Пошук за:</h3>
    <%= form_with url: cargoes_path, method: :get do |f| %>
    <div><%= f.select :search_for, ['назвою', 'цінністю',
                              'масою', 'реєстраційним номером'] %>
    </div>
      <%= f.label :search, "Назва вантажу" %>
      <div><%= f.text_field :search %></div>
      <br>
      <%= submit_tag 'Пошук' %>
    <% end %>
    <br>
    <%= link_to 'Додати', "../cargoes/new" %>
  </main>
</div>

app/views/cargoes/new.html.erb
<div class="page">
  <main>
    <center><h1>Введіть данні про вантаж</h1></center>
    <%= form_for :cargoe, url: cargoes_path do |f| %>
      <%= f.label :name, "Назва вантажу" %>
      <div><%= f.text_field :name %></div>
      <%= f.label :value, "Цінність вантажу" %>
      <div><%= f.select :value, ['мінімальна', 'комфорт', 'висока'] %></div>
      <%= f.label :mass, "Маса" %>
      <div><%= f.number_field :mass %></div>
      <%= f.label :reg_number, "Реєстраційний номер" %>
      <div><%= f.number_field :reg_number %></div>
      <%= f.label :reg_number, "Id маршруту" %>
      <div><%= f.select(:route_id, Route.all.collect { |route| [route.id] }) %></div>
      <br>
      <div><%= f.submit "Додати" %></div>
    <% end %>
  </main>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Port</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <header>
      <%= link_to 'Гловна', "../" %>
      <%= link_to 'Вантажі', cargoes_path %>
      <%= link_to 'Порти', ship_ports_path %>
      <%= link_to "Маршрути", routes_path %>
      <%= link_to "Кораблі", ships_path %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/ports/new.html.erb
<div class="page">
  <center><h1>Введіть данні про порт</h1></center>
  <%= form_for :port, url: ports_path do |f| %>
    <%= f.label :name, "Назва порту" %>
    <div><%= f.text_field :name %></div>
    <%= f.label :location, "Місце розміщення" %>
    <div><%= f.text_field :location %></div>
    <div><%= f.submit "Додати" %></div>
  <% end %>
</div>

app/views/routes/edit.html.erb
<h3>Змінити маршрут №<%= @route.id %></h3>
<%= form_for @route, method: :patch do |f| %>
  <%= f.label :ship_id, "Код корабля" %>
  <div><%= f.select(:ship_id, Ship.all.collect { |ship| [ship.name, ship.id] }, html_options: { style: { width: '100px' } }) %></div>
  <%= f.label :from_port_id, "Код порту відправки" %>
  <div><%= f.select(:from_port_id, ShipPort.all.collect { |ship| [ship.name, ship.id] }) %></div>
  <%= f.label :to_port_id, "Код порту призначення" %>
  <div><%= f.select(:to_port_id, ShipPort.all.collect { |ship| [ship.name, ship.id] }) %></div>
  <%= f.label :departure_time, "Дата відпливу" %>
  <div><%= f.time_field :departure_time %></div>
  <%= f.label :arrival_time, "Дата прибування" %>
  <div><%= f.time_field :arrival_time %></div>
  <div><%= f.submit 'Зберегти' %></div>
<% end %>

app/views/routes/index.html.erb
<div class="page">
  <main>
    <center><h1>Виведення данних про маршрути</h1></center>
    <table border="1">
      <tr>
       <th>Id</th>
       <th>Назва корабля</th>
       <th>Назва порту відправки</th>
       <th>Назва порту призначення</th>
       <th>Дата відправки</th>
       <th>Дата призначення</th>
      </tr>
      <% @routes.each do |route| %>
      <tr>
        <td><%= route.id %></td><td><%= route.ship.name %></td>
        <td><%= route.from_port.name %></td><td><%= route.to_port.name %></td>
        <td><%= route.departure_time.strftime("%H:%M") %></td>
        <td><%= route.arrival_time.strftime("%H:%M") %></td>
        <td><%= link_to 'Редагувати', edit_route_path(route) %></td>
        <td><%= link_to 'Видалити', route_path(route), method: :delete %></td>
      </tr>
      <% end %>
      </table>
      <br>
      <%= link_to 'Додати', "../routes/new" %>
  </main>
</div>

app/views/routes/new.html.erb
<div class="page">
  <center><h1>Введіть данні про маршрут</h1></center>
  <%= form_for :route, url: routes_path do |f| %>
    <%= f.label :ship_id, "Код корабля" %>
    <div><%= f.select(:ship_id, Ship.all.collect { |ship| [ship.name, ship.id] }, html_options: { style: { width: '100px' } }) %></div>
    <%= f.label :from_port_id, "Код порту відправки" %>
    <div><%= f.select(:from_port_id, ShipPort.all.collect { |ship| [ship.name, ship.id] }) %></div>
    <%= f.label :to_port_id, "Код порту призначення" %>
    <div><%= f.select(:to_port_id, ShipPort.all.collect { |ship| [ship.name, ship.id] }) %></div>
    <%= f.label :departure_time, "Дата відпливу" %>
    <div><%= f.time_field :departure_time %></div>
    <%= f.label :arrival_time, "Дата прибування" %>
    <div><%= f.time_field :arrival_time %></div>
    <div><%= f.submit "Додати" %></div>
  <% end %>
</div>

app/views/ship_ports/edit.html.erb
<h3>Змінити порт №<%= @port.id %></h3>
<%= form_for @port, method: :patch do |f| %>
<%= f.label :name, "Назва порту" %>
<div><%= f.text_field :name %></div>
<%= f.label :location, "Місце розміщення" %>
<div><%= f.text_field :location %></div>
  <div><%= f.submit 'Зберегти' %></div>
<% end %>

app/views/ship_ports/index.html.erb
<div class="page">
  <main>
    <center><h1>Виведення данних про порти</h1></center>
    <table border="1">
      <tr>
       <th>Id</th>
       <th>Назва порту</th>
       <th>Місце розташування</th>
      </tr>
      <% @ports.each do |port| %>
      <tr>
        <td><%= port.id %></td><td><%= port.name %></td>
        <td><%= port.location %></td>
        <td><%= link_to 'Редагувати', edit_ship_port_path(port) %></td>
        <td><%= link_to 'Видалити', ship_port_path(port), method: :delete %></td>
      </tr>
      <% end %>
    </table>
    <h3>Сортування за назвою</h3>
    <%= form_with url: ship_ports_path, method: :get do |f| %>
      <div><%= f.select :sort, ['від а до я', 'від я до а'] %></div>
      <br>
      <%= submit_tag 'Сортувати' %>
    <% end %>
    <h3>Пошук за назвою порту</h3>
    <%= form_with url: ship_ports_path, method: :get do |f| %>
      <%= f.label :search_name, "Назва порту" %>
      <div><%= f.text_field :search_name %></div>
      <br>
      <%= submit_tag 'Пошук' %>
    <% end %>
    <br>
    <%= link_to 'Додати порт', new_ship_port_path %>
  </main>
</div>

app/views/ship_ports/new.html.erb
<div class="page">
  <center><h1>Введіть данні про порт</h1></center>
  <%= form_for ShipPort.new do |f| %>
    <%= f.label :name, "Назва порту" %>
    <div><%= f.text_field :name %></div>
    <%= f.label :location, "Місце розміщення" %>
    <div><%= f.text_field :location %></div>
    <div><%= f.submit "Додати" %></div>
  <% end %>
</div>

app/views/ships/edit.html.erb
<h3>Змінити корабель №<%= @ship.id %></h3>
<%= form_for @ship, method: :patch do |f| %>
  <%= f.label :reg_number, "Реєстраційний номер" %>
  <div><%= f.number_field :reg_number %></div>
  <%= f.label :name, "Назва корабля" %>
  <div><%= f.text_field :name %></div>
  <%= f.label :load_capacity, "Вантажопідйомність" %>
  <div><%= f.number_field :load_capacity %></div>
  <div><%= f.submit 'Зберегти' %></div>
<% end %>

app/views/ships/index.html.erb
<div class="page">
  <main>
    <center><h1>Виведення данних про кораблі</h1></center>
    <table border="1">
      <tr>
       <th>Id</th>
       <th>Реєстраційний номер</th>
       <th>Назва корабля</th>
       <th>Вантажопідйомність в кг</th>
      </tr>
      <% @ships.each do |ship| %>
        <tr>
          <td><%= ship.id %></td><td><%= ship.reg_number %></td>
          <td><%= ship.name %></td><td><%= ship.load_capacity %></td>
          <td><%= link_to 'Редагувати', edit_ship_path(ship) %></td>
          <td><%= link_to 'Видалити', ship_path(ship), method: :delete %></td>
        </tr>
      <% end %>
    </table>
    <h3>Сортування за назвою корабля</h3>
    <%= form_with url: "../ships/", method: :get do |f| %>
      <div><%= f.select :sort, ['від а до я', 'від я до а'] %></div>
      <br>
      <%= submit_tag 'Сортувати' %>
    <% end %>
    <h3>Пошук за назвою корабля</h3>
    <%= form_with url: "../ships/", method: :get do |f| %>
      <%= f.label :search_name, "Назва корабля" %>
      <div><%= f.text_field :search_name %></div>
      <br>
      <%= submit_tag 'Пошук' %>
    <% end %>
    <br>
    <%= link_to 'Додати', "../ships/new" %>
  </main>
</div>

app/views/ships/new.html.erb
<div class="page">
  <center><h1>Введіть данні про корабель</h1></center>
  <%= form_for :ship, url: ships_path do |f| %>
    <%= f.label :reg_number, "Реєстраційний номер" %>
    <div><%= f.number_field :reg_number %></div>
    <%= f.label :name, "Назва корабля" %>
    <div><%= f.text_field :name %></div>
    <%= f.label :load_capacity, "Вантажопідйомність" %>
    <div><%= f.number_field :load_capacity %></div>
    <div><%= f.submit "Додати" %></div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="page">
  <main>
    <center><h1>Робота з базою даних порти</h1></center>
    <center><h3>Кругова діаграма</h3></center>
    <div>
      <%= pie_chart({ "Кораблі" => @ships, "Маршрути" => @routes,
                      "Вантажі" => @cargoes, "Порти" => @ports }) %>
    </div>
    <center><h3>Лінійна діаграма</h3></center>
    <div>
      <%= line_chart({ "Кораблі" => @ships, "Маршрути" => @routes,
                      "Вантажі" => @cargoes, "Порти" => @ports }) %>
    </div>
    <center><h3>Стопчикова діаграма</h3></center>
    <div>
      <%= column_chart({ "Кораблі" => @ships, "Маршрути" => @routes,
                      "Вантажі" => @cargoes, "Порти" => @ports }) %>
    </div>
    <center><h3>Гістограма</h3></center>
    <div>
      <%= bar_chart({ "Кораблі" => @ships, "Маршрути" => @routes,
                      "Вантажі" => @cargoes, "Порти" => @ports }) %>
    </div>
  </main>
</div>